### ISSUE TITLE
this.message.awaitbuttons Is Not A Function

### ISSUE THREAD

**Issue by mastercuber55** [ValuWaurld/discord-menu-buttons#1]
**At /src/menu.js**

**Comment by ValuWaurld** [comment]
Hey, are you sure that you're setting up the discord-buttons module correctly in your index? (cf the "Setup" documentation of the module @ https://discord-buttons.js.org/docs/stable/getting-started/setup.html)
If you do, could you provide me some of your code and tell me which line is causing this error?
Thanks !

**Comment by huntressofthefallen** [comment]
this.message.awaitButtons is not a function
    at Menu.awaitButtons (/app/node_modules/discord-menu-buttons/src/Menu.js:92:44)
