### ISSUE TITLE
Feature request + bug

### ISSUE THREAD

**Issue by JagritThukral** [ValuWaurld/discord-menu-buttons#2]
Whenever i click rewind button ⏪ the menu stops functioning with displaying this interaction failed .
Pls disable rewind and back button at first page and disable fast-forward and next button at last page

**Comment by legendary0001** [comment]
Package previously but now its not functioning due to unkown reason

**Comment by legendary0001** [comment]
@ValuWaurld pls

**Comment by legendary0001** [comment]
@ValuWaurld helooooooooo

**Comment by JagritThukral** [comment]
@ValuWaurld
